### PR TITLE
feat: change return value of extract_spans

### PR DESCRIPTION
**Pull request by callegarimattia**
Made extract_spans return the Span class

### CODE REVIEW

**Comment by krishnasism** [comment]
Can you do a 0.3.x release before merging this in please

**Review by krishnasism — APPROVED** [review]

**Comment by callegarimattia** [comment]
> Also can you please update the documentation for the functions? If anywhere it is mentioned `list[list[HotCharacter]]` for `extract_span` function - change it to the new implementation

Done :)

**Comment by callegarimattia** [comment]
Now code is compliant with the following:

- pycodestyle
- pyflakes
- pyupgrade
- flake8-bugbear
- flake8-simplify
- isort
- MaccaBe (complexity = 10)

**Comment by callegarimattia** [comment]
@krishnasism When you can check if the docs are ok :)
From my side we can merge!

**Comment by krishnasism** [comment]
I'll update docs to this PR and merge!

**Comment by krishnasism** [comment]
I merged it - I will update the docs in a separate PR :)

**Pull request merged**
