### PR TITLE
Add User Guide documentation

### PR DESCRIPTION
**Pull request by krishnasism**
- Added User Guide for better explanation of functions.
Issue: https://github.com/weareprestatech/hotpdf/issues/32

### CODE REVIEW

**Comment by krishnasism** [comment]
@callegarimattia I opened a PR for https://github.com/weareprestatech/hotpdf/issues/32

If you want me to wait and add docs for the new functions that you will push, I can do that. Or I can also open another PR later.

**Comment by callegarimattia** [comment]
Opened my pr #58 

Should I add extract_span_text() which incorporates the to_text() function?

I think it's better to give the List[Spans], instead of List[List[Hotchars]] and add a to_text() method to the Span class.

It's worth thinking about having a standard notation like: 

1. extract_span_text -> str
2. extract_span -> Span

**Comment by krishnasism** [comment]
Lgtm. 

Yes we could also add extract_span_text yes. To keep compatibility and let the user just use it easily.

**Comment by krishnasism** [comment]
Ok then wait to merge this. I'll add docs for your new functions and then I'll merge it in

**Comment by callegarimattia** [comment]
Oke, I'll make a pr for them

**Review by callegarimattia — APPROVED** [review]

**Pull request merged**
